---
# Source: tempo-distributed/templates/service-gossip-ring.yaml
apiVersion: v1
kind: Service
metadata:
  name: tempo-tempo-distributed-gossip-ring
  namespace: monitoring
  labels:
    app.kubernetes.io/component: tempo-tempo-distributed-gossip-ring
    helm.sh/chart: tempo-distributed-0.11.0
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: gossip-ring
      port: 7946
      protocol: TCP
      targetPort: http-memberlist
  selector:
    tempo-gossip-member: "true"
