---
# Source: tempo-distributed/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tempo-tempo-distributed
  labels:
    helm.sh/chart: tempo-distributed-0.11.0
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm
