---
# Source: tempo-distributed/templates/querier/service-querier.yaml
apiVersion: v1
kind: Service
metadata:
  name: tempo-tempo-distributed-querier
  namespace: monitoring
  labels:
    helm.sh/chart: tempo-distributed-0.11.0
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: querier
spec:
  ports:
    - name: http
      port: 3100
      protocol: TCP
      targetPort: 3100
    - name: grpc
      port: 9095
      protocol: TCP
      targetPort: 9095
  selector:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: querier
