---
# Source: loki/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: grafana-loki
  namespace: monitoring
  labels:
    app: loki
    chart: loki-2.8.1
    heritage: Helm
    release: grafana
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [grafana-loki]
