---
# Source: loki/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grafana-loki
  namespace: monitoring
  labels:
    app: loki
    chart: loki-2.8.1
    release: grafana
    heritage: Helm
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
    - port: 3100
      protocol: TCP
      name: http-metrics
      targetPort: http-metrics
  selector:
    app: loki
    release: grafana
