---
# Source: tempo-distributed/templates/memcached/service-memcached.yaml
apiVersion: v1
kind: Service
metadata:
  name: tempo-tempo-distributed-memcached
  namespace: monitoring
  labels:
    helm.sh/chart: tempo-distributed-0.11.0
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/version: "1.2.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: memcached
spec:
  ports:
  - name: memcached-client
    port: 11211
    targetPort: 11211
  - name: http-metrics
    port: 9150
    targetPort: http-metrics
  selector:
    app.kubernetes.io/name: tempo-distributed
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/component: memcached
